name: CI

on: pull_request

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write
  pages: write
  id-token: write

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version-file: .dvmrc

      - name: Install
        run: deno install

      - name: Check format
        run: deno task format --check

      - name: Lint
        run: deno task lint

      - name: Check
        run: deno task check

      - name: Test
        run: |
          deno task test
          deno task coverage
